### ISSUE TITLE
Settings page sends me to Mail

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite#50]
Not sure how to word this one so I'm just gonna gif it:

On Firefox
![firefox](https://user-images.githubusercontent.com/54612963/73216957-690cc600-412d-11ea-88f6-bf4f35e431c2.gif)

On Chrome
![chrome](https://user-images.githubusercontent.com/54612963/73217178-cdc82080-412d-11ea-80af-8ef7f2b0f963.gif)

As you can see, even if I don't click anyhting at all, the Settings morph into the mail.

**Comment by Tuch-o** [comment]
Confirmed by Tele.

**Comment by arpee** [comment]
@Tuch-o - can't replicate - thinking it may have been fixed by something we did. Can you confirm?

**Comment by Tuch-o** [comment]
Still happening here, both on Chrome and Firefox 

![gif2](https://user-images.githubusercontent.com/54612963/74592518-84fedb80-4ff8-11ea-948b-d863fa4c9e60.gif)

![gif3](https://user-images.githubusercontent.com/54612963/74592576-fd659c80-4ff8-11ea-8484-01c9d16218b8.gif)

**Comment by Tuch-o** [comment]
Fixed, closing.
